apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fullstack-chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend #same in labels app
  template:
    metadata:
      name: backend-pod
      namespace: fullstack-chatapp
      labels:
        app: backend #same in matchlabels app
    spec:
      containers:
        - name: backend-chat-app
          image: shubhankar24/chat-app-backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: production
            - name: MONGODB_URI # MongoDb connection
              value: mongodb://mongoadmin:secret@mongodb:27017/dbname?authSource=admin
            - name: JWT_SECRET # JWT secret key
              valueFrom: 
                secretKeyRef:
                  name: chatapp-secret
                  key: jwt
            - name: PORT
              value: "5001"   