apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb #same in labels app
  template:
    metadata:
      name: mongodb-pod
      namespace: chatapp
      labels:
        app: mongodb #same in matchlabels app
    spec:
      containers:
        - name: mongodb-chat-app
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongoadmin
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc